global:
  scrape_interval: 5s
  scrape_timeout: 2s
  evaluation_interval: 5s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    scrape_timeout: 2s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 172.17.0.1:3020
          - 172.17.0.1:3021
          - 172.17.0.1:3022
          - 172.17.0.1:3023
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/#remote_write
remote_write:
  - url: https://prometheus-us-central1.grafana.net/api/prom/push
    # Timeout for requests to the remote write endpoint
    remote_timeout: 10s
    basic_auth:
      username: "6421"
      password: "${GRAFANA_HOSTED_PROMETHEUS_API_KEY}"
    queue_config:
      # Number of samples to buffer per shard before we start dropping them
      capacity: 1000
      # Maximum number of shards, i.e. amount of concurrency
      max_shards: 10
      min_shards: 1
      # Maximum number of samples per send
      max_samples_per_send: 1000
      batch_send_deadline: 5s
      max_retries: 3
      min_backoff: 30ms
      max_backoff: 100ms